apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-agents-auth.fullname" . }}-secret
  labels:
    {{- include "orbit-agents-auth.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }} 