{{- if .Values.secrets.postgres.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-crawler.fullname" . }}-postgres
  labels:
    {{- include "orbit-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.postgres.hostKey }}: {{ .Values.secrets.postgres.host | b64enc }}
  {{ .Values.secrets.postgres.portKey }}: {{ .Values.secrets.postgres.port | b64enc }}
  {{ .Values.secrets.postgres.databaseKey }}: {{ .Values.secrets.postgres.database | b64enc }}
  {{ .Values.secrets.postgres.usernameKey }}: {{ .Values.secrets.postgres.username | b64enc }}
  {{ .Values.secrets.postgres.passwordKey }}: {{ .Values.secrets.postgres.password | b64enc }}
---
{{- end }}

{{- if .Values.secrets.s3.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-crawler.fullname" . }}-s3
  labels:
    {{- include "orbit-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.s3.bucketKey }}: {{ .Values.secrets.s3.bucket | b64enc }}
  {{ .Values.secrets.s3.regionKey }}: {{ .Values.secrets.s3.region | b64enc }}
  {{- if .Values.secrets.s3.accessKeyId }}
  {{ .Values.secrets.s3.accessKeyIdKey }}: {{ .Values.secrets.s3.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.s3.secretAccessKey }}
  {{ .Values.secrets.s3.secretAccessKeyKey }}: {{ .Values.secrets.s3.secretAccessKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.s3.endpointUrl }}
  {{ .Values.secrets.s3.endpointUrlKey }}: {{ .Values.secrets.s3.endpointUrl | b64enc }}
  {{- end }}
---
{{- end }}

{{- if .Values.secrets.opensearch.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-crawler.fullname" . }}-opensearch
  labels:
    {{- include "orbit-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.opensearch.hostKey }}: {{ .Values.secrets.opensearch.host | b64enc }}
  {{ .Values.secrets.opensearch.portKey }}: {{ .Values.secrets.opensearch.port | b64enc }}
  {{ .Values.secrets.opensearch.indexKey }}: {{ .Values.secrets.opensearch.index | b64enc }}
  {{- if .Values.secrets.opensearch.username }}
  {{ .Values.secrets.opensearch.usernameKey }}: {{ .Values.secrets.opensearch.username | b64enc }}
  {{- end }}
  {{- if .Values.secrets.opensearch.password }}
  {{ .Values.secrets.opensearch.passwordKey }}: {{ .Values.secrets.opensearch.password | b64enc }}
  {{- end }}
---
{{- end }}

{{- if .Values.secrets.redis.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-crawler.fullname" . }}-redis
  labels:
    {{- include "orbit-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.redis.hostKey }}: {{ .Values.secrets.redis.host | b64enc }}
  {{ .Values.secrets.redis.portKey }}: {{ .Values.secrets.redis.port | b64enc }}
  {{- if .Values.secrets.redis.password }}
  {{ .Values.secrets.redis.passwordKey }}: {{ .Values.secrets.redis.password | b64enc }}
  {{- end }}
---
{{- end }}

{{- if .Values.secrets.mls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit-crawler.fullname" . }}-mls
  labels:
    {{- include "orbit-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.mls.apiKey }}
  {{ .Values.secrets.mls.apiKeyKey }}: {{ .Values.secrets.mls.apiKey | b64enc }}
  {{- end }}
{{- end }} 